// prisma/seed-data/settings.ts
export const defaultSettings = [
  {
    key: 'school_name',
    value: 'SMA Negeri 1',
    deskripsi: 'Nama Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_short_name',
    value: 'SMANSA',
    deskripsi: 'Nama Singkat Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_logo',
    value: '/uploads/images/logo.png',
    deskripsi: 'Logo Sekolah',
    tipe: 'file',
  },
  {
    key: 'school_favicon',
    value: '/uploads/images/favicon.ico',
    deskripsi: 'Favicon Website',
    tipe: 'file',
  },
  {
    key: 'school_address',
    value: 'Jl. Pendidikan No. 1, Jakarta Selatan',
    deskripsi: 'Alamat Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_phone',
    value: '(021) 1234567',
    deskripsi: 'Telepon Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_email',
    value: 'info@smansa.sch.id',
    deskripsi: 'Email Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_website',
    value: 'https://smansa.sch.id',
    deskripsi: 'Website Sekolah',
    tipe: 'text',
  },
  {
    key: 'accreditation',
    value: 'A',
    deskripsi: 'Akreditasi Sekolah',
    tipe: 'text',
  },
  {
    key: 'accreditation_year',
    value: '2023',
    deskripsi: 'Tahun Akreditasi',
    tipe: 'text',
  },
  {
    key: 'school_motto',
    value: 'Unggul dalam Prestasi, Mulia dalam Budi Pekerti',
    deskripsi: 'Motto Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_vision',
    value: 'Menjadi sekolah unggulan yang menghasilkan lulusan berprestasi, berkarakter, dan berwawasan global',
    deskripsi: 'Visi Sekolah',
    tipe: 'text',
  },
  {
    key: 'school_mission',
    value: JSON.stringify([
      'Menyelenggarakan pembelajaran berkualitas berbasis teknologi',
      'Mengembangkan potensi peserta didik secara holistik',
      'Membangun karakter dan budi pekerti luhur',
      'Meningkatkan profesionalisme tenaga pendidik',
      'Menciptakan lingkungan sekolah yang aman dan nyaman',
    ]),
    deskripsi: 'Misi Sekolah',
    tipe: 'json',
  },
  {
    key: 'social_facebook',
    value: 'https://facebook.com/smansa',
    deskripsi: 'Facebook Sekolah',
    tipe: 'text',
  },
  {
    key: 'social_instagram',
    value: 'https://instagram.com/smansa',
    deskripsi: 'Instagram Sekolah',
    tipe: 'text',
  },
  {
    key: 'social_youtube',
    value: 'https://youtube.com/smansa',
    deskripsi: 'Youtube Sekolah',
    tipe: 'text',
  },
  {
    key: 'social_twitter',
    value: 'https://twitter.com/smansa',
    deskripsi: 'Twitter Sekolah',
    tipe: 'text',
  },
  {
    key: 'google_analytics_id',
    value: '',
    deskripsi: 'Google Analytics ID',
    tipe: 'text',
  },
  {
    key: 'seo_title',
    value: 'SMA Negeri 1 - Sekolah Unggulan',
    deskripsi: 'SEO Title',
    tipe: 'text',
  },
  {
    key: 'seo_description',
    value: 'SMA Negeri 1 adalah sekolah unggulan dengan akreditasi A',
    deskripsi: 'SEO Description',
    tipe: 'text',
  },
  {
    key: 'seo_keywords',
    value: 'sma, sekolah, pendidikan, smansa',
    deskripsi: 'SEO Keywords',
    tipe: 'text',
  },
  {
    key: 'smtp_host',
    value: 'smtp.gmail.com',
    deskripsi: 'SMTP Host',
    tipe: 'text',
  },
  {
    key: 'smtp_port',
    value: '587',
    deskripsi: 'SMTP Port',
    tipe: 'number',
  },
  {
    key: 'smtp_user',
    value: '',
    deskripsi: 'SMTP Username',
    tipe: 'text',
  },
  {
    key: 'ppdb_open',
    value: 'false',
    deskripsi: 'Status PPDB',
    tipe: 'boolean',
  },
  {
    key: 'ppdb_year',
    value: '2024',
    deskripsi: 'Tahun PPDB',
    tipe: 'text',
  },
  {
    key: 'ppdb_quota',
    value: '360',
    deskripsi: 'Kuota PPDB',
    tipe: 'number',
  },
  {
    key: 'maintenance_mode',
    value: 'false',
    deskripsi: 'Mode Maintenance',
    tipe: 'boolean',
  },
];